name: SNOMED translator deployment
run-name: SNOMED translator deployment in prod 🚀
on: [push]
jobs:
  Test-textmining-common-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bash action
        uses: nlp4bia-bsc/textmining-common-actions/actions/get-ssh-key@v1.0.1
        with:
          example_input: 'EJEMPLOOOOOOO'